### ISSUE TITLE
Add error and help popovers for array field

### ISSUE THREAD

**Issue by IgorZiegler** [hwdtech/smartforms#51]
Popovers should be splitted into two versions:
1. "Error" popover: popover with red text and x mark in heading (which should close the popover)
2. "Help" popover: should reproduce current behavior

**Comment by 102** [comment]
Duplicate #48

**Comment by 102** [comment]
@IgorZiegler what's the current status of this? Could you describe what's done and what's should be done?

**Comment by 102** [comment]
@IgorZiegler isn't this fixed in #59?
